spring:
  application:
    name: api-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 4081

#    global-filter:
#      -LoggingGlobalFilter
#      routes:
#        - id: method_route
#          uri: http://localhost:4081/
#          predicates:
#            - Path=/api/**, /payment/**
#            - Method=GET,POST
#          filters:
#            -RedirectionFilter
#            -BeforeRedirectionFilter